"""Declarative base and the shared column vocabulary.

The ``type_annotation_map`` below is load-bearing, not cosmetic. Declaring a
column as ``Mapped[Money]`` is the only sanctioned way to store an amount, and
it resolves to ``numeric(18, 4)``. There is deliberately no mapping from
``float`` to any SQL type, so a float money column fails at import time rather
than silently losing paise in production.
"""

from __future__ import annotations

import datetime as dt
import uuid
from decimal import Decimal
from typing import Annotated, Any

from sqlalchemy import DateTime, ForeignKey, Index, MetaData, Numeric, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

# Explicit naming convention so autogenerated migrations produce stable,
# reviewable constraint names instead of Postgres defaults.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

# --- Column vocabulary ------------------------------------------------------

#: Any monetary amount. numeric(18, 4) / Decimal. Never float.
Money = Annotated[Decimal, mapped_column(Numeric(18, 4))]

#: A percentage or ratio expressed as a number, e.g. a GST rate of 18.0000.
Rate = Annotated[Decimal, mapped_column(Numeric(9, 4))]

#: A 0..1 confidence score. Four decimals is plenty and keeps it comparable.
Confidence = Annotated[Decimal, mapped_column(Numeric(5, 4))]


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map = {  # noqa: RUF012
        Decimal: Numeric(18, 4),
        str: Text(),
        dt.datetime: DateTime(timezone=True),
        uuid.UUID: PgUUID(as_uuid=True),
        dict[str, Any]: JSONB,
        list[Any]: JSONB,
    }

    def __repr__(self) -> str:
        pk = getattr(self, "id", None)
        return f"<{type(self).__name__} id={pk}>"


class UUIDPrimaryKey:
    """UUID primary keys generated by the database via pgcrypto."""

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )


class TimestampMixin:
    created_at: Mapped[dt.datetime] = mapped_column(
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        server_default=func.now(),
        nullable=False,
    )


class TenantMixin:
    """Marks a table as tenant-scoped.

    Two consequences, both enforced elsewhere and both required:

    1. ``tenant_id`` is NOT NULL with an index, because every query against
       this table carries a tenant predicate.
    2. Migration 0002 must enable *and force* row-level security on the table
       and attach a policy. ``tests/test_schema_rls_coverage.py`` walks the
       subclasses of this mixin and fails if any table is missing either, so a
       new table added in a later phase cannot quietly ship without isolation.
    """

    @declared_attr.directive
    @classmethod
    def tenant_id(cls) -> Mapped[uuid.UUID]:
        return mapped_column(
            ForeignKey("tenant.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )


def tenant_scoped_index(table: str, *columns: str, unique: bool = False) -> Index:
    """Build an index that always leads with ``tenant_id``.

    Leading with the tenant column matches the shape of every real query and
    keeps the RLS predicate index-backed.
    """
    name = f"{'uq' if unique else 'ix'}_{table}_{'_'.join(('tenant_id', *columns))}"
    return Index(name, "tenant_id", *columns, unique=unique)
