"""Canonical schema: tenants, parties, documents, ledger, banking, links, findings, audit

Revision ID: 0001
Revises:
Create Date: 2026-07-25

Hand-written rather than autogenerated so the ordering, the constraint names
and the deliberate *absence* of certain constraints are all reviewable.

Notable choices, expanded in docs/DECISIONS.md:
  * All money is numeric(18, 4). No exceptions, no floats.
  * There is no unique constraint on (tenant_id, party_id, type, number) for
    documents. The findings engine must be able to *detect* duplicate and
    repeated invoice numbers, so the schema has to permit them.
  * bank_txn.amount is always positive; direction is a separate enum.
  * Row-level security is added in 0002, not here.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql as pg

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# --- Enum types -------------------------------------------------------------
ENUMS: dict[str, tuple[str, ...]] = {
    "membership_role": ("owner", "accountant", "reviewer", "read_only"),
    "party_kind": ("vendor", "customer", "both", "employee"),
    "document_type": (
        "purchase_invoice",
        "sales_invoice",
        "receipt",
        "expense",
        "ledger",
        "bank_statement",
        "credit_note",
        "debit_note",
        "delivery_note",
        "purchase_order",
        "unknown",
    ),
    "extraction_status": (
        "pending",
        "extracting",
        "extracted",
        "needs_review",
        "reviewed",
        "failed",
    ),
    "entity_type": (
        "document",
        "line_item",
        "ledger_entry",
        "bank_txn",
        "party",
        "source_file",
    ),
    "link_type": (
        "bank_txn_settles_document",
        "ledger_entry_for_document",
        "bank_txn_to_ledger_entry",
        "document_fulfils_document",
        "document_offsets_document",
        "gstr2b_matches_document",
        "duplicate_of",
    ),
    "link_status": ("proposed", "auto_accepted", "accepted", "rejected"),
    "finding_severity": ("info", "low", "medium", "high", "critical"),
    "finding_status": ("open", "acknowledged", "resolved", "false_positive"),
    "txn_direction": ("debit", "credit"),
}


def _enum(name: str) -> pg.ENUM:
    """Reference an already-created type; never create it implicitly."""
    return pg.ENUM(*ENUMS[name], name=name, create_type=False)


# All money is numeric(18, 4). These aliases exist so a reviewer can grep the
# migration and confirm no column uses anything else.
MONEY = sa.Numeric(18, 4)
RATE = sa.Numeric(9, 4)
CONFIDENCE = sa.Numeric(5, 4)


def upgrade() -> None:
    bind = op.get_bind()

    # --- Extensions ---------------------------------------------------------
    # citext: case-insensitive email equality without lower() everywhere.
    # pg_trgm: trigram indexes for party-name and narration fuzzy search, so
    #          Phase 2 blocking is index-backed rather than a sequential scan.
    # btree_gist: lets a uuid share a GiST index with an int4range, used for
    #          the page-ownership lookup on document.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    for name, values in ENUMS.items():
        pg.ENUM(*values, name=name).create(bind, checkfirst=True)

    # --- updated_at trigger -------------------------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )

    # --- tenant -------------------------------------------------------------
    op.create_table(
        "tenant",
        sa.Column("id", pg.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  primary_key=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("gstin", sa.Text()),
        sa.Column("pan", sa.Text()),
        sa.Column("country", sa.Text(), nullable=False, server_default="IN"),
        sa.Column("base_currency", sa.Text(), nullable=False, server_default="INR"),
        sa.Column("fy_start_month", sa.Integer(), nullable=False, server_default="4"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.UniqueConstraint("slug", name="uq_tenant_slug"),
        sa.CheckConstraint("fy_start_month BETWEEN 1 AND 12",
                           name="ck_tenant_fy_start_month_valid"),
        sa.CheckConstraint("char_length(base_currency) = 3",
                           name="ck_tenant_base_currency_iso4217"),
    )

    # --- app_user -----------------------------------------------------------
    # Global, not tenant-scoped: one CA-firm user works across many tenants.
    op.create_table(
        "app_user",
        sa.Column("id", pg.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  primary_key=True),
        sa.Column("email", pg.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text()),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("is_platform_admin", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("last_login_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.UniqueConstraint("email", name="uq_app_user_email"),
    )

    # --- membership ---------------------------------------------------------
    op.create_table(
        "membership",
        sa.Column("id", pg.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  primary_key=True),
        sa.Column("tenant_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("role", _enum("membership_role"), nullable=False),
        sa.Column("is_external_advisor", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE",
                                name="fk_membership_tenant_id_tenant"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE",
                                name="fk_membership_user_id_app_user"),
        sa.UniqueConstraint("tenant_id", "user_id", name="uq_membership_tenant_id_user_id"),
    )
    op.create_index("ix_membership_tenant_id", "membership", ["tenant_id"])
    op.create_index("ix_membership_user_id", "membership", ["user_id"])
    op.create_index("ix_membership_user_id_tenant_id", "membership", ["user_id", "tenant_id"])

    # --- party --------------------------------------------------------------
    op.create_table(
        "party",
        sa.Column("id", pg.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  primary_key=True),
        sa.Column("tenant_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("kind", _enum("party_kind"), nullable=False),
        sa.Column("legal_name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("gstin", sa.Text()),
        sa.Column("pan", sa.Text()),
        sa.Column("aliases", pg.JSONB(), nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("bank_accounts", pg.JSONB(), nullable=False,
                  server_default=sa.text("'[]'::jsonb")),
        sa.Column("payment_terms_days", sa.Integer()),
        sa.Column("is_first_time", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE",
                                name="fk_party_tenant_id_tenant"),
        sa.CheckConstraint("gstin IS NULL OR char_length(gstin) = 15",
                           name="ck_party_gstin_length"),
        sa.CheckConstraint("pan IS NULL OR char_length(pan) = 10", name="ck_party_pan_length"),
    )
    op.create_index("ix_party_tenant_id", "party", ["tenant_id"])
    op.create_index("ix_party_tenant_id_gstin", "party", ["tenant_id", "gstin"])
    op.create_index("ix_party_tenant_id_pan", "party", ["tenant_id", "pan"])
    op.execute(
        "CREATE INDEX ix_party_display_name_trgm ON party "
        "USING gin (display_name gin_trgm_ops)"
    )

    # --- source_file --------------------------------------------------------
    op.create_table(
        "source_file",
        sa.Column("id", pg.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  primary_key=True),
        sa.Column("tenant_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("mime", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("page_count", sa.Integer()),
        sa.Column("has_text_layer", sa.Boolean()),
        sa.Column("uploaded_by", pg.UUID(as_uuid=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE",
                                name="fk_source_file_tenant_id_tenant"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["app_user.id"], ondelete="SET NULL",
                                name="fk_source_file_uploaded_by_app_user"),
        # Content-hash dedupe: re-uploading the same bytes is a no-op.
        sa.UniqueConstraint("tenant_id", "sha256", name="uq_source_file_tenant_id_sha256"),
        sa.UniqueConstraint("storage_key", name="uq_source_file_storage_key"),
        sa.CheckConstraint("byte_size > 0", name="ck_source_file_byte_size_positive"),
        sa.CheckConstraint("page_count IS NULL OR page_count > 0",
                           name="ck_source_file_page_count_positive"),
    )
    op.create_index("ix_source_file_tenant_id", "source_file", ["tenant_id"])

    # --- document -----------------------------------------------------------
    op.create_table(
        "document",
        sa.Column("id", pg.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  primary_key=True),
        sa.Column("tenant_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("type", _enum("document_type"), nullable=False),
        sa.Column("number", sa.Text()),
        sa.Column("doc_date", sa.Date()),
        sa.Column("due_date", sa.Date()),
        sa.Column("party_id", pg.UUID(as_uuid=True)),
        sa.Column("currency", sa.Text(), nullable=False, server_default="INR"),
        sa.Column("subtotal", MONEY),
        sa.Column("tax_total", MONEY),
        sa.Column("grand_total", MONEY),
        sa.Column("source_file_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("page_range", pg.INT4RANGE(), nullable=False),
        sa.Column("extraction_status", _enum("extraction_status"), nullable=False,
                  server_default="pending"),
        sa.Column("field_confidence", pg.JSONB(), nullable=False,
                  server_default=sa.text("'{}'::jsonb")),
        sa.Column("extractor_adapter", sa.Text()),
        sa.Column("extractor_model_version", sa.Text()),
        sa.Column("prompt_hash", sa.Text()),
        sa.Column("extracted_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE",
                                name="fk_document_tenant_id_tenant"),
        # RESTRICT, not CASCADE: deleting a party must not silently destroy the
        # documents that justify its balances.
        sa.ForeignKeyConstraint(["party_id"], ["party.id"], ondelete="RESTRICT",
                                name="fk_document_party_id_party"),
        sa.ForeignKeyConstraint(["source_file_id"], ["source_file.id"], ondelete="RESTRICT",
                                name="fk_document_source_file_id_source_file"),
        sa.CheckConstraint("char_length(currency) = 3", name="ck_document_currency_iso4217"),
        sa.CheckConstraint("NOT isempty(page_range)", name="ck_document_page_range_non_empty"),
        sa.CheckConstraint("lower(page_range) >= 1", name="ck_document_page_range_one_based"),
    )
    op.create_index("ix_document_tenant_id", "document", ["tenant_id"])
    op.create_index("ix_document_party_id", "document", ["party_id"])
    op.create_index("ix_document_source_file_id", "document", ["source_file_id"])
    # NOTE: index, NOT unique. Duplicate detection needs duplicates to exist.
    op.create_index("ix_document_tenant_id_party_id_number", "document",
                    ["tenant_id", "party_id", "number"])
    op.create_index("ix_document_tenant_id_type_doc_date", "document",
                    ["tenant_id", "type", "doc_date"])
    op.create_index("ix_document_tenant_id_grand_total", "document",
                    ["tenant_id", "grand_total"])
    op.create_index("ix_document_tenant_id_extraction_status", "document",
                    ["tenant_id", "extraction_status"])
    # "Which document owns page 7 of this batch?" -> containment query.
    op.execute(
        "CREATE INDEX ix_document_source_file_id_page_range ON document "
        "USING gist (source_file_id, page_range)"
    )

    # --- line_item ----------------------------------------------------------
    op.create_table(
        "line_item",
        sa.Column("id", pg.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  primary_key=True),
        # Denormalised from document purely so the RLS policy binds to a local
        # column instead of requiring a join.
        sa.Column("tenant_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("document_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("hsn_sku", sa.Text()),
        sa.Column("qty", MONEY),
        sa.Column("rate", MONEY),
        sa.Column("tax_rate", RATE),
        sa.Column("amount", MONEY),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE",
                                name="fk_line_item_tenant_id_tenant"),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE",
                                name="fk_line_item_document_id_document"),
        sa.UniqueConstraint("document_id", "line_no", name="uq_line_item_document_id_line_no"),
        sa.CheckConstraint("line_no >= 1", name="ck_line_item_line_no_positive"),
    )
    op.create_index("ix_line_item_tenant_id", "line_item", ["tenant_id"])
    op.create_index("ix_line_item_document_id", "line_item", ["document_id"])
    op.create_index("ix_line_item_tenant_id_hsn_sku", "line_item", ["tenant_id", "hsn_sku"])

    # --- ledger_entry -------------------------------------------------------
    op.create_table(
        "ledger_entry",
        sa.Column("id", pg.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  primary_key=True),
        sa.Column("tenant_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("account", sa.Text(), nullable=False),
        sa.Column("debit", MONEY, nullable=False, server_default="0"),
        sa.Column("credit", MONEY, nullable=False, server_default="0"),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("document_id", pg.UUID(as_uuid=True)),
        sa.Column("source_file_id", pg.UUID(as_uuid=True)),
        sa.Column("party_id", pg.UUID(as_uuid=True)),
        sa.Column("narration", sa.Text()),
        sa.Column("voucher_type", sa.Text()),
        sa.Column("voucher_no", sa.Text()),
        sa.Column("external_id", sa.Text()),
        sa.Column("recorded_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE",
                                name="fk_ledger_entry_tenant_id_tenant"),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="SET NULL",
                                name="fk_ledger_entry_document_id_document"),
        sa.ForeignKeyConstraint(["source_file_id"], ["source_file.id"], ondelete="SET NULL",
                                name="fk_ledger_entry_source_file_id_source_file"),
        sa.ForeignKeyConstraint(["party_id"], ["party.id"], ondelete="SET NULL",
                                name="fk_ledger_entry_party_id_party"),
        sa.UniqueConstraint("tenant_id", "external_id",
                            name="uq_ledger_entry_tenant_id_external_id"),
        sa.CheckConstraint("debit >= 0 AND credit >= 0",
                           name="ck_ledger_entry_amounts_non_negative"),
        # A ledger line is one-sided. Both non-zero means the importer merged
        # two postings -- fail loudly rather than reconcile a fiction.
        sa.CheckConstraint("debit = 0 OR credit = 0", name="ck_ledger_entry_single_sided"),
    )
    op.create_index("ix_ledger_entry_tenant_id", "ledger_entry", ["tenant_id"])
    op.create_index("ix_ledger_entry_document_id", "ledger_entry", ["document_id"])
    op.create_index("ix_ledger_entry_tenant_id_account_entry_date", "ledger_entry",
                    ["tenant_id", "account", "entry_date"])

    # --- bank_account -------------------------------------------------------
    op.create_table(
        "bank_account",
        sa.Column("id", pg.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  primary_key=True),
        sa.Column("tenant_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("bank_name", sa.Text()),
        sa.Column("account_number_masked", sa.Text()),
        # Hash only. The employee-collusion rule needs equality, not the number.
        sa.Column("account_number_hash", sa.Text()),
        sa.Column("ifsc", sa.Text()),
        sa.Column("currency", sa.Text(), nullable=False, server_default="INR"),
        sa.Column("is_own", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("party_id", pg.UUID(as_uuid=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE",
                                name="fk_bank_account_tenant_id_tenant"),
        sa.ForeignKeyConstraint(["party_id"], ["party.id"], ondelete="SET NULL",
                                name="fk_bank_account_party_id_party"),
        sa.CheckConstraint("char_length(currency) = 3",
                           name="ck_bank_account_currency_iso4217"),
    )
    op.create_index("ix_bank_account_tenant_id", "bank_account", ["tenant_id"])
    op.create_index("ix_bank_account_tenant_id_account_number_hash", "bank_account",
                    ["tenant_id", "account_number_hash"])

    # --- bank_txn -----------------------------------------------------------
    op.create_table(
        "bank_txn",
        sa.Column("id", pg.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  primary_key=True),
        sa.Column("tenant_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("account_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("txn_date", sa.Date(), nullable=False),
        # Always positive; sign lives in `direction`.
        sa.Column("amount", MONEY, nullable=False),
        sa.Column("direction", _enum("txn_direction"), nullable=False),
        sa.Column("narration", sa.Text()),
        sa.Column("balance", MONEY),
        sa.Column("inferred_party_id", pg.UUID(as_uuid=True)),
        sa.Column("source_file_id", pg.UUID(as_uuid=True)),
        sa.Column("external_id", sa.Text()),
        sa.Column("value_date", sa.Date()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE",
                                name="fk_bank_txn_tenant_id_tenant"),
        sa.ForeignKeyConstraint(["account_id"], ["bank_account.id"], ondelete="CASCADE",
                                name="fk_bank_txn_account_id_bank_account"),
        sa.ForeignKeyConstraint(["inferred_party_id"], ["party.id"], ondelete="SET NULL",
                                name="fk_bank_txn_inferred_party_id_party"),
        sa.ForeignKeyConstraint(["source_file_id"], ["source_file.id"], ondelete="SET NULL",
                                name="fk_bank_txn_source_file_id_source_file"),
        sa.UniqueConstraint("tenant_id", "account_id", "external_id",
                            name="uq_bank_txn_tenant_id_account_id_external_id"),
        sa.CheckConstraint("amount > 0", name="ck_bank_txn_amount_positive"),
    )
    op.create_index("ix_bank_txn_tenant_id", "bank_txn", ["tenant_id"])
    op.create_index("ix_bank_txn_account_id", "bank_txn", ["account_id"])
    op.create_index("ix_bank_txn_inferred_party_id", "bank_txn", ["inferred_party_id"])
    # Blocking filters on a date window and an amount band; both index-backed.
    op.create_index("ix_bank_txn_tenant_id_txn_date_amount", "bank_txn",
                    ["tenant_id", "txn_date", "amount"])
    op.create_index("ix_bank_txn_tenant_id_amount", "bank_txn", ["tenant_id", "amount"])
    # Document-number-in-narration substring search.
    op.execute(
        "CREATE INDEX ix_bank_txn_narration_trgm ON bank_txn "
        "USING gin (narration gin_trgm_ops)"
    )

    # --- link ---------------------------------------------------------------
    # Polymorphic on both ends, so no foreign keys to the endpoints. Edge
    # integrity is the job of the Phase 2 traversal helpers.
    op.create_table(
        "link",
        sa.Column("id", pg.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  primary_key=True),
        sa.Column("tenant_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("from_type", _enum("entity_type"), nullable=False),
        sa.Column("from_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("to_type", _enum("entity_type"), nullable=False),
        sa.Column("to_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("link_type", _enum("link_type"), nullable=False),
        sa.Column("confidence", CONFIDENCE, nullable=False),
        sa.Column("matched_amount", MONEY),
        sa.Column("status", _enum("link_status"), nullable=False, server_default="proposed"),
        sa.Column("evidence", pg.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("matcher_version", sa.Text()),
        sa.Column("decided_by", pg.UUID(as_uuid=True)),
        sa.Column("decided_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE",
                                name="fk_link_tenant_id_tenant"),
        sa.ForeignKeyConstraint(["decided_by"], ["app_user.id"], ondelete="SET NULL",
                                name="fk_link_decided_by_app_user"),
        sa.UniqueConstraint("tenant_id", "from_type", "from_id", "to_type", "to_id",
                            "link_type", name="uq_link_endpoints"),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1",
                           name="ck_link_confidence_unit_interval"),
        sa.CheckConstraint("NOT (from_type = to_type AND from_id = to_id)",
                           name="ck_link_no_self_link"),
    )
    op.create_index("ix_link_tenant_id", "link", ["tenant_id"])
    op.create_index("ix_link_tenant_id_from_type_from_id", "link",
                    ["tenant_id", "from_type", "from_id"])
    op.create_index("ix_link_tenant_id_to_type_to_id", "link",
                    ["tenant_id", "to_type", "to_id"])
    op.create_index("ix_link_tenant_id_status_confidence", "link",
                    ["tenant_id", "status", "confidence"])

    # --- finding ------------------------------------------------------------
    op.create_table(
        "finding",
        sa.Column("id", pg.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  primary_key=True),
        sa.Column("tenant_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("rule_id", sa.Text(), nullable=False),
        sa.Column("severity", _enum("finding_severity"), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("entity_refs", pg.JSONB(), nullable=False,
                  server_default=sa.text("'[]'::jsonb")),
        sa.Column("evidence", pg.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("status", _enum("finding_status"), nullable=False, server_default="open"),
        sa.Column("dedupe_key", sa.Text(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("resolved_by", pg.UUID(as_uuid=True)),
        sa.Column("resolved_at", sa.DateTime(timezone=True)),
        sa.Column("resolution_note", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE",
                                name="fk_finding_tenant_id_tenant"),
        sa.ForeignKeyConstraint(["resolved_by"], ["app_user.id"], ondelete="SET NULL",
                                name="fk_finding_resolved_by_app_user"),
        # Re-running a rule updates the existing finding instead of stacking
        # duplicates in the inbox.
        sa.UniqueConstraint("tenant_id", "rule_id", "dedupe_key",
                            name="uq_finding_tenant_id_rule_id_dedupe_key"),
    )
    op.create_index("ix_finding_tenant_id", "finding", ["tenant_id"])
    op.create_index("ix_finding_tenant_id_status_severity", "finding",
                    ["tenant_id", "status", "severity"])
    op.create_index("ix_finding_tenant_id_rule_id", "finding", ["tenant_id", "rule_id"])

    # --- audit_log ----------------------------------------------------------
    # bigint identity rather than uuid: monotonic ordering gives cheap keyset
    # pagination over what will be the largest table here. Made immutable in
    # migration 0002.
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), primary_key=True),
        sa.Column("tenant_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("actor", pg.UUID(as_uuid=True)),
        sa.Column("actor_email", sa.Text()),
        sa.Column("actor_is_external", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", pg.UUID(as_uuid=True)),
        sa.Column("before", pg.JSONB()),
        sa.Column("after", pg.JSONB()),
        sa.Column("request_id", sa.Text()),
        sa.Column("ip", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE",
                                name="fk_audit_log_tenant_id_tenant"),
        sa.ForeignKeyConstraint(["actor"], ["app_user.id"], ondelete="SET NULL",
                                name="fk_audit_log_actor_app_user"),
    )
    op.create_index("ix_audit_log_tenant_id", "audit_log", ["tenant_id"])
    op.create_index("ix_audit_log_tenant_id_created_at", "audit_log",
                    ["tenant_id", "created_at"])
    op.create_index("ix_audit_log_tenant_id_entity_type_entity_id", "audit_log",
                    ["tenant_id", "entity_type", "entity_id"])
    op.create_index("ix_audit_log_tenant_id_actor", "audit_log", ["tenant_id", "actor"])

    # --- updated_at triggers ------------------------------------------------
    for table in (
        "tenant", "app_user", "membership", "party", "source_file", "document",
        "line_item", "ledger_entry", "bank_account", "bank_txn", "link", "finding",
    ):
        op.execute(
            f"CREATE TRIGGER trg_{table}_updated_at BEFORE UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )


def downgrade() -> None:
    for table in (
        "audit_log", "finding", "link", "bank_txn", "bank_account", "ledger_entry",
        "line_item", "document", "source_file", "party", "membership", "app_user", "tenant",
    ):
        op.drop_table(table)

    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")

    bind = op.get_bind()
    for name in ENUMS:
        pg.ENUM(name=name).drop(bind, checkfirst=True)
